### ISSUE TITLE
micro_ros_udp_freertos example fails with FSP > v3.8.0

### ISSUE THREAD

**Issue by gsokoll** [micro-ROS/micro_ros_renesas_demos#111] opened 2023-03-09 03:49 UTC
## Issue template

Hardware description: EV-RA6M5
RTOS: bare metal, freertos
Installation type: micro_ros_udp_freertos, e2studio v2022-07, Ubuntu 20.04
Version or commit hash: galactic

#### Steps to reproduce the issue
Cloned per "Getting started" instructions. Imported project into e2 Studio, built and ran code with agent running on Ubuntu host PC.  Agent IP address is specified in microros_thread_entry.c, and DHCP is enabled for FreeRTOS+TCP component.

Example works if the BSP configuration is set to use FSP versions 3.5.0 through to 3.8.0.

Example fails if FSP version 4.0.0 or higher is used, at line 20 of microros_app.c
```
18    //create init_options
19    rclc_support_t support;
20    RCCHECK(rclc_support_init(&support, 0, NULL, &allocator));

```
Return code from rclc_support_init() is 1 (RCL_RET_ERROR = unspecified error return code).  

Have not been able to debug further into rclc_support_init to understand why.

**Comment by Acuadros95** [comment] 2023-03-13 08:22
Hi @gsokoll,

Currently we don`t support FSP version 4.0.0, and it clearly breaks compatibility with 3.x versions.

> Have not been able to debug further into rclc_support_init to understand why.

The error is caused by internal changes on the transport calls, if you really need to use the FSP 4.0 you can try to debug and update the transport methods: [udp_transport_freeRTOS.c](https://github.com/micro-ROS/micro_ros_renesas2estudio_component/blob/humble/extra_sources/microros_transports/udp_transport_freeRTOS.c)

I am closing, as an update to this FSP version is expected but is not on our current roadmap.
Will update this issue when we tackle this update.

**Closed as completed by Acuadros95** 2023-03-13 08:22 UTC
